const fs = require('fs');
const path = require('path');
const Report = require('../models/Report');
const Alert = require('../models/Alert');
const Incident = require('../models/Incident');
const analyticsService = require('./analyticsService');
const threatIntelService = require('./threatIntelService');

const REPORTS_DIR = path.join(__dirname, '../../ai/reports');

const generateReport = async ({ type = 'EXECUTIVE_SUMMARY', format = 'JSON', dateRange = 'LAST_7_DAYS', generatedBy = 'System' }) => {
  if (!fs.existsSync(REPORTS_DIR)) {
    fs.mkdirSync(REPORTS_DIR, { recursive: true });
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const reportId = `RPT-${Date.now()}-${Math.floor(100 + Math.random() * 900)}`;

  let title = 'NetShield AI Executive Security Summary';
  let metricsData = {};
  let contentString = '';

  if (type === 'THREAT_INTEL') {
    title = 'Threat Intelligence Indicator & Telemetry Report';
    const intelOverview = await threatIntelService.getThreatIntelOverview();
    const intelList = await threatIntelService.getThreatIntelList({ limit: 50 });
    metricsData = { intelOverview, intelList: intelList.data };
  } else if (type === 'SECURITY_ANALYTICS') {
    title = 'Security Analytics & Network Attack Summary';
    const overview = await analyticsService.getOverview(dateRange);
    const attackDist = await analyticsService.getAttackDistribution(dateRange);
    const topSources = await analyticsService.getTopSources(10);
    const socMetrics = await analyticsService.getSocMetrics();
    metricsData = { overview, attackDist, topSources, socMetrics };
  } else if (type === 'ALERT_SUMMARY') {
    title = 'SOC Threat Alert Inspection & Resolution Report';
    const alerts = await Alert.find().sort({ timestamp: -1 }).limit(100).lean();
    metricsData = { totalCount: alerts.length, alerts };
  } else if (type === 'INCIDENT_REPORT') {
    title = 'Security Incident Investigation & Lifecycle Audit';
    const incidents = await Incident.find().sort({ createdAt: -1 }).limit(50).lean();
    metricsData = { totalCount: incidents.length, incidents };
  } else {
    title = 'Executive Cybersecurity Posture Summary';
    const overview = await analyticsService.getOverview(dateRange);
    const socMetrics = await analyticsService.getSocMetrics();
    metricsData = { overview, socMetrics, timestamp: new Date().toISOString() };
  }

  const ext = format.toLowerCase();
  const fileName = `report_${type.toLowerCase()}_${timestamp}.${ext}`;
  const filePath = path.join(REPORTS_DIR, fileName);

  if (format === 'CSV') {
    if (Array.isArray(metricsData.alerts)) {
      const header = 'AlertID,Timestamp,Severity,AttackType,SourceIP,DestinationIP,RiskScore,Status\n';
      const rows = metricsData.alerts.map(a =>
        `${a.alertId},${a.timestamp},${a.severity},${a.attackType},${a.sourceIp},${a.destinationIp},${a.riskScore},${a.status}`
      ).join('\n');
      contentString = header + rows;
    } else {
      contentString = `Metric,Value\nReportID,${reportId}\nType,${type}\nGeneratedBy,${generatedBy}\nGeneratedAt,${new Date().toISOString()}\n`;
    }
  } else if (format === 'PDF') {
    contentString = `[PDF EXPORT STREAM] ${title}\nReport ID: ${reportId}\nGenerated By: ${generatedBy}\nTimestamp: ${new Date().toISOString()}\n\nSummary Metrics:\n` + JSON.stringify(metricsData, null, 2);
  } else {
    contentString = JSON.stringify({ reportId, title, type, format, dateRange, generatedBy, generatedAt: new Date().toISOString(), metricsData }, null, 2);
  }

  fs.writeFileSync(filePath, contentString);

  const stats = fs.statSync(filePath);
  const sizeKb = `${Math.max(1, Math.round(stats.size / 1024))} KB`;

  const report = await Report.create({
    reportId,
    title,
    type,
    format,
    dateRange,
    generatedBy,
    fileUrl: `/api/reports/${fileName}/download`,
    fileSize: sizeKb,
    summary: `${title} generated in ${format} format for ${dateRange}`,
    metricsData
  });

  return report;
};

const getReportsList = async (query = {}) => {
  const filter = {};
  if (query.type) filter.type = query.type;
  if (query.format) filter.format = query.format.toUpperCase();

  const reports = await Report.find(filter).sort({ createdAt: -1 }).limit(50).lean();
  return reports;
};

const getReportById = async (reportId) => {
  const report = await Report.findOne({ reportId }).lean();
  if (!report) {
    throw new Error(`Report ${reportId} not found`);
  }
  return report;
};

module.exports = {
  generateReport,
  getReportsList,
  getReportById
};
